version: '3'

services:
  rabbit:
    build: thumbnail/rabbit
    image: skairunner/rabbit:latest
    hostname: somerabbit
    volumes:
      - rabbit-storage:/var/lib/rabbitmq
  flowerbox:
    image: skairunner/flower:latest
    ports:
      - "5555:5555"
    depends_on:
      - rabbit
  minio:
    build:
      context: thumbnail/
      dockerfile: minio.Dockerfile
    image: skairunner/minio:latest
    volumes:
      - minio-storage:/data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    ports:
      - "9000:9000"
  celeryworker:
    build:
      dockerfile: thumbnail/worker.Dockerfile
      context: .
    image: skairunner/imagescrap-test_worker:latest
    command: celery -A thumbnail worker -l info
    environment:
      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: minio123
      DATABASE_URL: postgres://pass:user@postgres:5432/imagescrapbook
    depends_on:
      - rabbit
      - minio
  workprovider:
    build:
      context: .
      dockerfile: thumbnail/workprovider/Dockerfile
    image: skairunner/imagescrap-workprovider:latest
    command: sh -c "python provide_work.py"
    ports:
      - "8000:8000"
      - "5555:5555"
    environment:
      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: minio123
    depends_on:
      - minio
      - rabbit
      - celeryworker
  postgres:
    image: postgres:11
    environment:
      POSTGRES_USER: pass
      POSTGRES_PASSWORD: user
      POSTGRES_DB: imagescrapbook
    ports:
      - "2345:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  appserver:
    build:
      context: .
      dockerfile: imagescrapbook/Dockerfile
    image: skairunner/imagescrap-appserver
    command: runserver 0.0.0.0:8000 #migrate --fake 
    environment:
      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: minio123
      DATABASE_URL: postgres://pass:user@postgres:5432/imagescrapbook
    ports:
    - "8000:8000"
    depends_on:
      - postgres

volumes:
  pgdata:
  minio-storage:
  rabbit-storage:
