version: '3'

services:
  rabbit:
    build: ./rabbit
    image: skairunner/rabbit:latest
    hostname: somerabbit
    volumes:
      - rabbit-storage:/var/lib/rabbitmq
  flowerbox:
    image: skairunner/flower:latest
    ports:
      - "5555:5555"
    depends_on:
      - rabbit
  minio:
    build:
      context: .
      dockerfile: minio.Dockerfile
    image: skairunner/minio:latest
    volumes:
      - minio-storage:/data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    ports:
      - "9000:9000"
  celeryworker:
    build:
      dockerfile: worker.Dockerfile
      context: .
    image: skairunner/imagescrap-test_worker:latest
    command: celery -A thumbnail worker -l info
    environment:
      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: minio123
    depends_on:
      - rabbit
      - minio
  workprovider:
    build:
      context: .
      dockerfile: workprovider/Dockerfile
    image: skairunner/imagescrap-workprovider:latest
    command: sh -c "python provide_work.py"
    ports:
      - "8000:8000"
      - "5555:5555"
    environment:
      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: minio123
    depends_on:
      - minio
      - rabbit
      - celeryworker

volumes:
  minio-storage:
  rabbit-storage:

networks:
  default:
    external:
      name: backend_default
