version: '3'

services:
  rabbit:
    build: ./rabbit
    hostname: somerabbit
    volumes:
      - rabbit-storage:/var/lib/rabbitmq
  minio:
    build:
      context: .
      dockerfile: minio.Dockerfile
    volumes:
      - minio-storage:/data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    ports:
      - "9000:9000"
  celeryworker:
    build:
      dockerfile: worker.Dockerfile
      context: .
    command: celery -A thumbnail worker -l info
    depends_on:
      - rabbit
      - minio
  workprovider:
    build:
      context: .
      dockerfile: workprovider/Dockerfile
    command: sh -c "python provide_work.py & flower -A thumbnail --port=5555"
    ports:
      - "8000:8000"
      - "5555:5555"
    environment:
      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: minio123
    depends_on:
      - minio
      - rabbit
      - celeryworker

volumes:
  minio-storage:
  rabbit-storage:
