apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: flowerbox
  name: flowerbox
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: flowerbox
    spec:
      containers:
      - image: skairunner/flower:latest
        name: flowerbox
        ports:
        - containerPort: 5555
        resources: {}
      restartPolicy: Always
status: {}
