apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: workprovider
  name: workprovider
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: workprovider
    spec:
      containers:
      - args:
        - sh
        - -c
        - python provide_work.py
        env:
        - name: AWS_ACCESS_KEY_ID
          value: minio
        - name: AWS_SECRET_ACCESS_KEY
          value: minio123
        image: skairunner/imagescrap-workprovider:latest
        name: workprovider
        ports:
        - containerPort: 8000
        - containerPort: 5555
        resources: {}
      restartPolicy: Always
status: {}
