apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: appserver
  name: appserver
spec:
  type: LoadBalancer
  ports:
  - name: "outside"
    port: 80
    targetPort: 8000
  selector:
    io.kompose.service: appserver
status:
  loadBalancer: {}
