apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: appserver
  name: appserver
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: appserver
    spec:
      containers:
      - args:
        - runserver
        - 0.0.0.0:8000
        env:
        - name: AWS_ACCESS_KEY_ID
          value: minio
        - name: AWS_SECRET_ACCESS_KEY
          value: minio123
        - name: DATABASE_URL
          value: postgres://pass:user@postgres:5432/imagescrapbook
        - name: PYTHONUNBUFFERED
          value: "0"
        image: skairunner/imagescrap-appserver
        name: appserver
        ports:
        - containerPort: 8000
        resources: {}
      restartPolicy: Always
status: {}
